name: Server

# on:
#   push:
#     branches:
#       - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Install required tools
        run: |
          npm i firebase-tools
          (cd functions && npm i)

      - name: Deploy
        run: |
          firebase deploy
        with:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
